tenant:
  organizationId: ""     # Organization ID
  organizationName: ""   # Organization Name
  id: ""                 # Tenant ID
  instanceType: ""       # Instance Type

vpa:                     # Vertical pod autoscaler configurations
  central:               # Central VPA configuration
    enabled: true
    recommenders:
      - name: prometheus
    updatePolicy:
      updateMode: "Auto"
      minReplicas: 1
    resourcePolicy:
      containerPolicies:
        - containerName: "*"
          minAllowed:
            cpu: "100m"
            memory: "250Mi"
          maxAllowed:
            cpu: "1.5"
            memory: "18Gi"
