{{- if ((.Values.vpa).central).enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: central-vpa
  namespace: {{ .Release.Namespace }}
  labels: {{- include "tenant-resources.labels" . | nindent 4 }}
  annotations: {{- include "tenant-resources.annotations" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       "Deployment"
    name:       "central"
  {{- if .Values.vpa.central.updatePolicy }}
  updatePolicy: {{ toYaml .Values.vpa.central.updatePolicy | nindent 4 }}
  {{- end }}
  {{- if .Values.vpa.central.resourcePolicy }}
  resourcePolicy: {{ toYaml .Values.vpa.central.resourcePolicy | nindent 4 }}
  {{- end }}
  {{- if .Values.vpa.central.recommenders }}
  recommenders: {{ toYaml .Values.vpa.central.recommenders | nindent 4 }}
  {{- end }}
{{ end }}
